NIGEP_AVAILABLE_KWARGS = [
    'execution_name',
    'model',
    'batch_size',
    'input_shape',
    'x_data',
    'y_data',
    'target_names',
    'class_mode',
    'k_fold_n',
    'epochs',
    'callbacks',
    'save_models',
    'evaluate_models',
]
